// This is an auto-generated TEMPLATE file for Stage 3 (GUI) integration
// DO NOT use this file directly - gui-agent will adapt it to your plugin structure

#include "PluginEditor.h"

// UI resource binary data (generated by CMake)
extern const char* _binary_index_html_start;
extern const char* _binary_index_html_size;
extern const char* _binary_index_js_start;
extern const char* _binary_index_js_size;

//==============================================================================
CodoxAudioProcessorEditor::CodoxAudioProcessorEditor (CodoxAudioProcessor& p)
    : AudioProcessorEditor (&p), audioProcessor (p)
    // ========================================================================
    // 1️⃣ RELAY INITIALIZATION (order matches header declaration)
    // ========================================================================
    , masterVolumeRelay(std::make_unique<juce::WebSliderRelay>("master_volume"))
    // OSC A
    , oscAWavetableRelay(std::make_unique<juce::WebComboBoxRelay>("osc_a_wavetable"))
    , oscAPositionRelay(std::make_unique<juce::WebSliderRelay>("osc_a_position"))
    , oscALevelRelay(std::make_unique<juce::WebSliderRelay>("osc_a_level"))
    , oscAPanRelay(std::make_unique<juce::WebSliderRelay>("osc_a_pan"))
    , oscAOctaveRelay(std::make_unique<juce::WebComboBoxRelay>("osc_a_octave"))
    , oscASemitoneRelay(std::make_unique<juce::WebSliderRelay>("osc_a_semitone"))
    , oscAFineRelay(std::make_unique<juce::WebSliderRelay>("osc_a_fine"))
    , oscAWarpModeRelay(std::make_unique<juce::WebComboBoxRelay>("osc_a_warp_mode"))
    , oscAWarpAmountRelay(std::make_unique<juce::WebSliderRelay>("osc_a_warp_amount"))
    // OSC B
    , oscBWavetableRelay(std::make_unique<juce::WebComboBoxRelay>("osc_b_wavetable"))
    , oscBPositionRelay(std::make_unique<juce::WebSliderRelay>("osc_b_position"))
    , oscBLevelRelay(std::make_unique<juce::WebSliderRelay>("osc_b_level"))
    , oscBPanRelay(std::make_unique<juce::WebSliderRelay>("osc_b_pan"))
    , oscBOctaveRelay(std::make_unique<juce::WebComboBoxRelay>("osc_b_octave"))
    , oscBSemitoneRelay(std::make_unique<juce::WebSliderRelay>("osc_b_semitone"))
    , oscBFineRelay(std::make_unique<juce::WebSliderRelay>("osc_b_fine"))
    , oscBWarpModeRelay(std::make_unique<juce::WebComboBoxRelay>("osc_b_warp_mode"))
    , oscBWarpAmountRelay(std::make_unique<juce::WebSliderRelay>("osc_b_warp_amount"))
    // Sub + Noise
    , subShapeRelay(std::make_unique<juce::WebComboBoxRelay>("sub_shape"))
    , subOctaveRelay(std::make_unique<juce::WebComboBoxRelay>("sub_octave"))
    , subLevelRelay(std::make_unique<juce::WebSliderRelay>("sub_level"))
    , noiseTypeRelay(std::make_unique<juce::WebComboBoxRelay>("noise_type"))
    , noiseLevelRelay(std::make_unique<juce::WebSliderRelay>("noise_level"))
    // Filter
    , filterTypeRelay(std::make_unique<juce::WebComboBoxRelay>("filter_type"))
    , filterCutoffRelay(std::make_unique<juce::WebSliderRelay>("filter_cutoff"))
    , filterResonanceRelay(std::make_unique<juce::WebSliderRelay>("filter_resonance"))
    , filterDriveRelay(std::make_unique<juce::WebSliderRelay>("filter_drive"))
    , filterEnvDepthRelay(std::make_unique<juce::WebSliderRelay>("filter_env_depth"))
    , filterKeytrackRelay(std::make_unique<juce::WebSliderRelay>("filter_keytrack"))
    // Amp Envelope
    , ampAttackRelay(std::make_unique<juce::WebSliderRelay>("amp_attack"))
    , ampDecayRelay(std::make_unique<juce::WebSliderRelay>("amp_decay"))
    , ampSustainRelay(std::make_unique<juce::WebSliderRelay>("amp_sustain"))
    , ampReleaseRelay(std::make_unique<juce::WebSliderRelay>("amp_release"))
    // Filter Envelope
    , filtAttackRelay(std::make_unique<juce::WebSliderRelay>("filt_attack"))
    , filtDecayRelay(std::make_unique<juce::WebSliderRelay>("filt_decay"))
    , filtSustainRelay(std::make_unique<juce::WebSliderRelay>("filt_sustain"))
    , filtReleaseRelay(std::make_unique<juce::WebSliderRelay>("filt_release"))
    // LFOs
    , lfo1ShapeRelay(std::make_unique<juce::WebComboBoxRelay>("lfo1_shape"))
    , lfo1RateRelay(std::make_unique<juce::WebSliderRelay>("lfo1_rate"))
    , lfo1SyncRelay(std::make_unique<juce::WebToggleButtonRelay>("lfo1_sync"))
    , lfo2ShapeRelay(std::make_unique<juce::WebComboBoxRelay>("lfo2_shape"))
    , lfo2RateRelay(std::make_unique<juce::WebSliderRelay>("lfo2_rate"))
    , lfo2SyncRelay(std::make_unique<juce::WebToggleButtonRelay>("lfo2_sync"))
    , lfo3ShapeRelay(std::make_unique<juce::WebComboBoxRelay>("lfo3_shape"))
    , lfo3RateRelay(std::make_unique<juce::WebSliderRelay>("lfo3_rate"))
    , lfo3SyncRelay(std::make_unique<juce::WebToggleButtonRelay>("lfo3_sync"))
    , lfo4ShapeRelay(std::make_unique<juce::WebComboBoxRelay>("lfo4_shape"))
    , lfo4RateRelay(std::make_unique<juce::WebSliderRelay>("lfo4_rate"))
    , lfo4SyncRelay(std::make_unique<juce::WebToggleButtonRelay>("lfo4_sync"))
    // Macros + Voice
    , macro1Relay(std::make_unique<juce::WebSliderRelay>("macro1"))
    , macro2Relay(std::make_unique<juce::WebSliderRelay>("macro2"))
    , macro3Relay(std::make_unique<juce::WebSliderRelay>("macro3"))
    , macro4Relay(std::make_unique<juce::WebSliderRelay>("macro4"))
    , unisonVoicesRelay(std::make_unique<juce::WebComboBoxRelay>("unison_voices"))
    , unisonDetuneRelay(std::make_unique<juce::WebSliderRelay>("unison_detune"))
    , glideTimeRelay(std::make_unique<juce::WebSliderRelay>("glide_time"))
    // Effects
    , fxDistortionMixRelay(std::make_unique<juce::WebSliderRelay>("fx_distortion_mix"))
    , fxChorusMixRelay(std::make_unique<juce::WebSliderRelay>("fx_chorus_mix"))
    , fxPhaserMixRelay(std::make_unique<juce::WebSliderRelay>("fx_phaser_mix"))
    , fxFlangerMixRelay(std::make_unique<juce::WebSliderRelay>("fx_flanger_mix"))
    , fxDelayMixRelay(std::make_unique<juce::WebSliderRelay>("fx_delay_mix"))
    , fxReverbMixRelay(std::make_unique<juce::WebSliderRelay>("fx_reverb_mix"))
    , fxEqMixRelay(std::make_unique<juce::WebSliderRelay>("fx_eq_mix"))
    , fxCompressorMixRelay(std::make_unique<juce::WebSliderRelay>("fx_compressor_mix"))
    // ========================================================================
    // 2️⃣ WEBVIEW INITIALIZATION (register all relays via .withOptionsFrom())
    // ========================================================================
    , webView(std::make_unique<juce::WebBrowserComponent>(
        juce::WebBrowserComponent::Options{}
            .withBackend(juce::WebBrowserComponent::Options::Backend::webview2)
            .withWinWebView2Options(
                juce::WebBrowserComponent::Options::WinWebView2{}
                    .withUserDataFolder(juce::File::getSpecialLocation(
                        juce::File::SpecialLocationType::tempDirectory))
                    .withBuiltInErrorPageDisabled()
                    .withStatusBarDisabled())
            .withResourceProvider(
                [](const juce::String& url) -> std::optional<juce::WebBrowserComponent::Resource>
                {
                    // Serve index.html
                    if (url == "https://juce.backend/index.html" || url == "https://juce.backend/")
                    {
                        return juce::WebBrowserComponent::Resource {
                            juce::MemoryBlock(_binary_index_html_start, 
                                            (size_t)_binary_index_html_size),
                            "text/html"
                        };
                    }
                    
                    // Serve JUCE frontend library
                    if (url == "https://juce.backend/js/juce/index.js")
                    {
                        return juce::WebBrowserComponent::Resource {
                            juce::MemoryBlock(_binary_index_js_start,
                                            (size_t)_binary_index_js_size),
                            "application/javascript"  // CRITICAL: Correct MIME type
                        };
                    }
                    
                    return std::nullopt;
                },
                juce::WebBrowserComponent::Options::Backend::webview2)
            // Register all relays
            .withOptionsFrom(*masterVolumeRelay)
            .withOptionsFrom(*oscAWavetableRelay)
            .withOptionsFrom(*oscAPositionRelay)
            .withOptionsFrom(*oscALevelRelay)
            .withOptionsFrom(*oscAPanRelay)
            .withOptionsFrom(*oscAOctaveRelay)
            .withOptionsFrom(*oscASemitoneRelay)
            .withOptionsFrom(*oscAFineRelay)
            .withOptionsFrom(*oscAWarpModeRelay)
            .withOptionsFrom(*oscAWarpAmountRelay)
            .withOptionsFrom(*oscBWavetableRelay)
            .withOptionsFrom(*oscBPositionRelay)
            .withOptionsFrom(*oscBLevelRelay)
            .withOptionsFrom(*oscBPanRelay)
            .withOptionsFrom(*oscBOctaveRelay)
            .withOptionsFrom(*oscBSemitoneRelay)
            .withOptionsFrom(*oscBFineRelay)
            .withOptionsFrom(*oscBWarpModeRelay)
            .withOptionsFrom(*oscBWarpAmountRelay)
            .withOptionsFrom(*subShapeRelay)
            .withOptionsFrom(*subOctaveRelay)
            .withOptionsFrom(*subLevelRelay)
            .withOptionsFrom(*noiseTypeRelay)
            .withOptionsFrom(*noiseLevelRelay)
            .withOptionsFrom(*filterTypeRelay)
            .withOptionsFrom(*filterCutoffRelay)
            .withOptionsFrom(*filterResonanceRelay)
            .withOptionsFrom(*filterDriveRelay)
            .withOptionsFrom(*filterEnvDepthRelay)
            .withOptionsFrom(*filterKeytrackRelay)
            .withOptionsFrom(*ampAttackRelay)
            .withOptionsFrom(*ampDecayRelay)
            .withOptionsFrom(*ampSustainRelay)
            .withOptionsFrom(*ampReleaseRelay)
            .withOptionsFrom(*filtAttackRelay)
            .withOptionsFrom(*filtDecayRelay)
            .withOptionsFrom(*filtSustainRelay)
            .withOptionsFrom(*filtReleaseRelay)
            .withOptionsFrom(*lfo1ShapeRelay)
            .withOptionsFrom(*lfo1RateRelay)
            .withOptionsFrom(*lfo1SyncRelay)
            .withOptionsFrom(*lfo2ShapeRelay)
            .withOptionsFrom(*lfo2RateRelay)
            .withOptionsFrom(*lfo2SyncRelay)
            .withOptionsFrom(*lfo3ShapeRelay)
            .withOptionsFrom(*lfo3RateRelay)
            .withOptionsFrom(*lfo3SyncRelay)
            .withOptionsFrom(*lfo4ShapeRelay)
            .withOptionsFrom(*lfo4RateRelay)
            .withOptionsFrom(*lfo4SyncRelay)
            .withOptionsFrom(*macro1Relay)
            .withOptionsFrom(*macro2Relay)
            .withOptionsFrom(*macro3Relay)
            .withOptionsFrom(*macro4Relay)
            .withOptionsFrom(*unisonVoicesRelay)
            .withOptionsFrom(*unisonDetuneRelay)
            .withOptionsFrom(*glideTimeRelay)
            .withOptionsFrom(*fxDistortionMixRelay)
            .withOptionsFrom(*fxChorusMixRelay)
            .withOptionsFrom(*fxPhaserMixRelay)
            .withOptionsFrom(*fxFlangerMixRelay)
            .withOptionsFrom(*fxDelayMixRelay)
            .withOptionsFrom(*fxReverbMixRelay)
            .withOptionsFrom(*fxEqMixRelay)
            .withOptionsFrom(*fxCompressorMixRelay)
    ))
    // ========================================================================
    // 3️⃣ ATTACHMENT INITIALIZATION (bind parameters to relays)
    // ========================================================================
    , masterVolumeAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("master_volume"), *masterVolumeRelay))
    // OSC A
    , oscAWavetableAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_a_wavetable"), *oscAWavetableRelay))
    , oscAPositionAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_a_position"), *oscAPositionRelay))
    , oscALevelAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_a_level"), *oscALevelRelay))
    , oscAPanAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_a_pan"), *oscAPanRelay))
    , oscAOctaveAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_a_octave"), *oscAOctaveRelay))
    , oscASemitoneAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_a_semitone"), *oscASemitoneRelay))
    , oscAFineAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_a_fine"), *oscAFineRelay))
    , oscAWarpModeAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_a_warp_mode"), *oscAWarpModeRelay))
    , oscAWarpAmountAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_a_warp_amount"), *oscAWarpAmountRelay))
    // OSC B
    , oscBWavetableAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_b_wavetable"), *oscBWavetableRelay))
    , oscBPositionAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_b_position"), *oscBPositionRelay))
    , oscBLevelAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_b_level"), *oscBLevelRelay))
    , oscBPanAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_b_pan"), *oscBPanRelay))
    , oscBOctaveAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_b_octave"), *oscBOctaveRelay))
    , oscBSemitoneAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_b_semitone"), *oscBSemitoneRelay))
    , oscBFineAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_b_fine"), *oscBFineRelay))
    , oscBWarpModeAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_b_warp_mode"), *oscBWarpModeRelay))
    , oscBWarpAmountAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("osc_b_warp_amount"), *oscBWarpAmountRelay))
    // Sub + Noise
    , subShapeAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("sub_shape"), *subShapeRelay))
    , subOctaveAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("sub_octave"), *subOctaveRelay))
    , subLevelAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("sub_level"), *subLevelRelay))
    , noiseTypeAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("noise_type"), *noiseTypeRelay))
    , noiseLevelAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("noise_level"), *noiseLevelRelay))
    // Filter
    , filterTypeAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("filter_type"), *filterTypeRelay))
    , filterCutoffAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("filter_cutoff"), *filterCutoffRelay))
    , filterResonanceAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("filter_resonance"), *filterResonanceRelay))
    , filterDriveAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("filter_drive"), *filterDriveRelay))
    , filterEnvDepthAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("filter_env_depth"), *filterEnvDepthRelay))
    , filterKeytrackAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("filter_keytrack"), *filterKeytrackRelay))
    // Amp Envelope
    , ampAttackAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("amp_attack"), *ampAttackRelay))
    , ampDecayAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("amp_decay"), *ampDecayRelay))
    , ampSustainAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("amp_sustain"), *ampSustainRelay))
    , ampReleaseAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("amp_release"), *ampReleaseRelay))
    // Filter Envelope
    , filtAttackAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("filt_attack"), *filtAttackRelay))
    , filtDecayAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("filt_decay"), *filtDecayRelay))
    , filtSustainAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("filt_sustain"), *filtSustainRelay))
    , filtReleaseAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("filt_release"), *filtReleaseRelay))
    // LFOs
    , lfo1ShapeAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("lfo1_shape"), *lfo1ShapeRelay))
    , lfo1RateAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("lfo1_rate"), *lfo1RateRelay))
    , lfo1SyncAttachment(std::make_unique<juce::WebToggleButtonParameterAttachment>(
        *audioProcessor.parameters.getParameter("lfo1_sync"), *lfo1SyncRelay))
    , lfo2ShapeAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("lfo2_shape"), *lfo2ShapeRelay))
    , lfo2RateAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("lfo2_rate"), *lfo2RateRelay))
    , lfo2SyncAttachment(std::make_unique<juce::WebToggleButtonParameterAttachment>(
        *audioProcessor.parameters.getParameter("lfo2_sync"), *lfo2SyncRelay))
    , lfo3ShapeAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("lfo3_shape"), *lfo3ShapeRelay))
    , lfo3RateAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("lfo3_rate"), *lfo3RateRelay))
    , lfo3SyncAttachment(std::make_unique<juce::WebToggleButtonParameterAttachment>(
        *audioProcessor.parameters.getParameter("lfo3_sync"), *lfo3SyncRelay))
    , lfo4ShapeAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("lfo4_shape"), *lfo4ShapeRelay))
    , lfo4RateAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("lfo4_rate"), *lfo4RateRelay))
    , lfo4SyncAttachment(std::make_unique<juce::WebToggleButtonParameterAttachment>(
        *audioProcessor.parameters.getParameter("lfo4_sync"), *lfo4SyncRelay))
    // Macros + Voice
    , macro1Attachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("macro1"), *macro1Relay))
    , macro2Attachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("macro2"), *macro2Relay))
    , macro3Attachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("macro3"), *macro3Relay))
    , macro4Attachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("macro4"), *macro4Relay))
    , unisonVoicesAttachment(std::make_unique<juce::WebComboBoxParameterAttachment>(
        *audioProcessor.parameters.getParameter("unison_voices"), *unisonVoicesRelay))
    , unisonDetuneAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("unison_detune"), *unisonDetuneRelay))
    , glideTimeAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("glide_time"), *glideTimeRelay))
    // Effects
    , fxDistortionMixAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("fx_distortion_mix"), *fxDistortionMixRelay))
    , fxChorusMixAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("fx_chorus_mix"), *fxChorusMixRelay))
    , fxPhaserMixAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("fx_phaser_mix"), *fxPhaserMixRelay))
    , fxFlangerMixAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("fx_flanger_mix"), *fxFlangerMixRelay))
    , fxDelayMixAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("fx_delay_mix"), *fxDelayMixRelay))
    , fxReverbMixAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("fx_reverb_mix"), *fxReverbMixRelay))
    , fxEqMixAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("fx_eq_mix"), *fxEqMixRelay))
    , fxCompressorMixAttachment(std::make_unique<juce::WebSliderParameterAttachment>(
        *audioProcessor.parameters.getParameter("fx_compressor_mix"), *fxCompressorMixRelay))
{
    // Set editor size (from v6-ui.yaml window dimensions)
    setSize (1200, 800);

    // Add WebView to editor
    addAndMakeVisible(*webView);

    // Navigate to local page
    webView->goToURL("https://juce.backend/index.html");
}

CodoxAudioProcessorEditor::~CodoxAudioProcessorEditor()
{
    // Attachments destroyed first (reverse order)
    // Then webView destroyed
    // Then relays destroyed last
    // This order prevents crashes during plugin reload
}

//==============================================================================
void CodoxAudioProcessorEditor::paint (juce::Graphics& g)
{
    // WebView fills entire area - no painting needed
    g.fillAll (juce::Colours::black);
}

void CodoxAudioProcessorEditor::resized()
{
    // WebView fills entire editor area
    webView->setBounds(getLocalBounds());
}
